server:
  port : 8081

spring:
  application:
    name: visanet
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/

grpc:
  client:
    response-code-service:
      address: static://localhost:8083
      negotiationType: plaintext