server:
  port : 8082

spring:
  application:
    name: credibanco
  zipkin:
    enabled: true

grpc:
  client:
    response-code-service:
      address: static://localhost:8083
      negotiationType: plaintext