grpc:
  port: 8083
  enableReflection: true
  shutdownGrace: 30

spring:
  main:
    web-application-type: none
  sleuth:
    grpc:
      enabled: true
  application:
    name: response-gRPC
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/