server:
  port : 8080

feign:
  client:
    config:
      visanet-feign-client:
        url: http://localhost:8081
        connectTimeout: 300
        readTimeout: 5000
        loggerLevel: basic
      credibanco-feign-client:
        url: http://localhost:8082
        connectTimeout: 300
        readTimeout: 5000
        loggerLevel: basic